revole issue for build workflow ``` Run export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity --query 'Account' | tr -d '"')   export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity --query 'Account' | tr -d '"')   export CDK_DEFAULT_REGION=${AWS_REGION}   npx projen build   shell: /usr/bin/bash -e {0}   env:     CI: true     AWS_REGION: ap-northeast-1     AWS_ACCESS_KEY_ID: ***     AWS_SECRET_ACCESS_KEY: *** npm WARN exec The following package was not found and will be installed: projen@0.70.7 👾 build » default | node .projenrc.js node:internal/modules/cjs/loader:1024   throw err;   ^
Error: Cannot find module 'projen'
Require stack:
- /home/runner/work/cdk-emrserverless-with-delta-lake/cdk-emrserverless-with-delta-lake/.projenrc.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/runner/work/cdk-emrserverless-with-delta-lake/cdk-emrserverless-with-delta-lake/.projenrc.js:1:25)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/cdk-emrserverless-with-delta-lake/cdk-emrserverless-with-delta-lake/.projenrc.js'
  ]
}
👾 Task "build » default" failed when executing "node .projenrc.js" (cwd: /home/runner/work/cdk-emrserverless-with-delta-lake/cdk-emrserverless-with-delta-lake)
Error: Process completed with exit code 1.
```